app:
  provider:
    name: ${PROVIDER_NAME}
    token: ${PROVIDER_API_TOKEN}
    url: ${PROVIDER_API_URL}

spring:
  application:
    name: translator
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${SERVER_PORT}

logging:
  config: classpath:log4j2-plain.xml
#  level:
#    root: debug
#    org:
#      springframework:
#        web: trace
#      apache: trace
#debug: true
